baseURL = 'https://coopshap.com/'
languageCode = 'en-us'
title = 'Coop Academy'
theme = 'tailbliss'

params = {moto = 'Under Construction', description = 'For Lab section, visit https://www.coopshap.com/ECE1181/', social_media = {github = {enabled = false}}}
