baseURL: ''
title: CooperSense
languageCode: en-us
DefaultContentLanguage: en
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
paginate: 9
darkmode_js:
  - assets/js/darkmode.js
enableInlineShortcodes: true

markup:
  goldmark:
    extensions:
      definitionList: true 
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: true

params:
  author: Cooper Shapard
  authorimage: ../assets/images/global/author.webp
  og_image: /images/tailbliss-cover.png
  moto: "Portfolio and More, v1.1.2"
  description: ""
  disable_theme_toggle: true
  disable_stay_uptodate: true

  p1:
    heading: "Steno-Anki Engine"
    image: "images/pages/StenoAnki.png"
    url: https://github.com/cshapard26/steno-anki-engine
    content:
      - text: "Steno-Anki engine is a CLI tool that efficiently parses, decodes, and creates stenographic briefs to export in a format that Anki natively supports."
      - text: "Originally built to manage Clippy2 files for Plover, it was later extended to support custom dictionaries, phoneticize results, and use a fine-tuned GPT model to generate custom briefs."
      - text: "Useful for both beginning and advanced stenographers to help improve speed and reduce the toil of brief creation and memorization."
    links:
      - text: Go give it a ⭐ on GitHub!
        url: "https://github.com/cshapard26/steno-anki-engine"

  p2:
    heading: "Membrane"
    image: "images/pages/Membrane.png"
    url: https://github.com/cshapard26/Membrane
    content:
      - text: "Membrane, a.k.a MembraneChain, is a blockchain-based solution to securely and transparently share research data. By using technologies such as Zero-Knowledge Proofs, One-Time Keys, and Commit-and-Reveal protocol, it ensures attribution of traded data and allows users to choose exactly who can and cannot touch the data they share."
      - text: "The project is currently in development, and I am working alongside 2 PhD students and 1 post-doctorate student to bring Membrane to the world. A paper with our methods is currently underway to be published in a conference hosted by IEEE."
    links:
      - text: "Check out our progress on GitHub"
        url: https://github.com/cshapard26/Membrane
  
  p3:
    heading: "Book Folding Commissions"
    url: /bookfolding
    content:
      - text: "Book folding is the art of cutting and folding the pages of a book to bring out a three-dimensional image, and it is one of my favorite hobbies. They say a picture is worth a thousand words, so why not turn a thousand words into a picture?"
      - text: "The process is very time consuming, yet surprisingly soothing. Each page is hand-marked, cut, and folded, often more than twenty times per page depending on the desired detail. A simple name usually takes around eight hours. Something as complex as a face can take well over thirty hours to finish."
      - text: "Due to interest in my art, I am open to commissions and would happily take on any project you have in mind."
    links:
      - text: Interested? Visit the Book Folding page to learn more and order!
        url: "/bookfolding"
    image1: "images/pages/jontebook.jpg"
    image2: "images/pages/ronaldobook.jpg"
    image3: "images/pages/malfoybook.jpg"
    image4: "images/pages/bookerbook.jpg"
    image5: "images/pages/crumbook.jpg"

  p4:
    heading: "Recent Posts"
    content:
      - text: "Find more by clicking the tags or viewing a category in the top right"
      
  p5:
    heading: "Stay Up to Date"
    content:
      - text: "Sagittis scelerisque nulla cursus in enim consectetur quam. Dictum urna sed consectetur neque tristique pellentesque."
    action: "#"
    label: "Email address"
    placeholder: "Enter your email"
    button: "Notify me"

  social_media:
    github:
      enabled: true
      url: 'https://github.com/cshapard26'
    facebook:
      enabled: false
      url: 'https://facebook.com/nusserstudios'
    instagram:
      enabled: false
      url: 'https://instagram.com/nusserstudios'
    linkedin:
      enabled: true
      url: 'https://www.linkedin.com/in/coopershapard/'
    kofi:
      enabled: false
      url: 'https://ko-fi.com/coopshap'

menu:
  main:
    - identifier: labcategories
      pre: dropdown
      name: Labs
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 30
    - identifier: about
      name: Courses
      url: /courses/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 40
  labcategories:
    - identifier: ece1181
      name: ECE1181
      url: 'https://www.coopshap.com/ECE1181/'
      weight: 10
  dropdown:
    - identifier: appearance
      pre: stars # can be stars, comments or piechart
      name: Appearance
      post: "Easy customization"
      url: "#"
      weight: 10
    - identifier: comments
      pre: comments # can be stars, comments or piechart
      name: Comments
      post: "Check your latest comments"
      url: "#"
      weight: 20
    - identifier: analytics
      pre: piechart # can be stars, comments or piechart
      name: Analytics
      post: "Take a look at your statistics"
      url: "#"
      weight: 30
  footer:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: rules
      name: Policy
      url: /policy/
      weight: 20
    - identifier: funding
      name: Donate
      url: https://venmo.com/the-singularity
      weight: 100


markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: Categories
  tag: Tags

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

module:
  hugoVersion:
    extended: true
    min: "0.104.0"
